name: Deploy to Master

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Archive files
        run: tar -cvzf dist.tar.gz -C dist/app .

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OVH_SSH_HOST }}
          username: ${{ secrets.OVH_SSH_USER }}
          password: ${{ secrets.OVH_SSH_PASSWORD }}
          source: "dist.tar.gz"
          target: "/home/eccemiz/app"

      - name: Extract files on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_SSH_HOST }}
          username: ${{ secrets.OVH_SSH_USER }}
          password: ${{ secrets.OVH_SSH_PASSWORD }}
          script: |
            cd /home/eccemiz/app
            tar -xvzf dist.tar.gz
            rm dist.tar.gz
